# Generated by Django 2.1.dev20180125184051 on 2018-01-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='note',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
